import { MigrationInterface, QueryRunner } from 'typeorm';

export class TimestampToTaiwanTime1778992132593 implements MigrationInterface {
    name = 'TimestampToTaiwanTime1778992132593';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE "supportSchedule" DROP CONSTRAINT IF EXISTS "supportSchedule_dayOfWeek_check"');
        await queryRunner.query('ALTER TABLE "supportSession" DROP CONSTRAINT IF EXISTS "supportSession_satisfactionRating_check"');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" DROP CONSTRAINT IF EXISTS "CK_supportKnowledgeBase_priority"');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" DROP CONSTRAINT IF EXISTS "CK_supportKnowledgeBase_replyType"');
        await queryRunner.query('ALTER TABLE "supportSchedule" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "isAccessible" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "hasParking" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "hasTransit" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "updatedAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "organization" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "conIntroduction"');
        await queryRunner.query('ALTER TABLE "concert" ADD "conIntroduction" character varying(30000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "conAddress"');
        await queryRunner.query('ALTER TABLE "concert" ADD "conAddress" character varying(2000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "ticketPurchaseMethod"');
        await queryRunner.query('ALTER TABLE "concert" ADD "ticketPurchaseMethod" character varying(10000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "precautions"');
        await queryRunner.query('ALTER TABLE "concert" ADD "precautions" character varying(20000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "refundPolicy"');
        await queryRunner.query('ALTER TABLE "concert" ADD "refundPolicy" character varying(10000)');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'ConInfoStatus\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."ConInfoStatus" RENAME TO "ConInfoStatus_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."concert_coninfostatus_enum" AS ENUM(\'draft\', \'reviewing\', \'published\', \'rejected\', \'finished\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" TYPE "public"."concert_coninfostatus_enum" USING "conInfoStatus"::"text"::"public"."concert_coninfostatus_enum"');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" SET DEFAULT \'draft\'');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."ConInfoStatus_old"');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'ReviewStatus\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."ReviewStatus" RENAME TO "ReviewStatus_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."concert_reviewstatus_enum" AS ENUM(\'pending\', \'approved\', \'rejected\', \'skipped\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" TYPE "public"."concert_reviewstatus_enum" USING "reviewStatus"::"text"::"public"."concert_reviewstatus_enum"');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" SET DEFAULT \'skipped\'');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "visitCount" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "updatedAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concertSession" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "ticketType" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'TicketStatus\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."TicketStatus" RENAME TO "TicketStatus_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."ticket_status_enum" AS ENUM(\'purchased\', \'refunded\', \'used\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "ticket" ALTER COLUMN "status" TYPE "public"."ticket_status_enum" USING "status"::"text"::"public"."ticket_status_enum"');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."TicketStatus_old"');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'OrderStatus\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."OrderStatus" RENAME TO "OrderStatus_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."order_orderstatus_enum" AS ENUM(\'held\', \'expired\', \'paid\', \'cancelled\', \'refunded\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "order" ALTER COLUMN "orderStatus" TYPE "public"."order_orderstatus_enum" USING "orderStatus"::"text"::"public"."order_orderstatus_enum"');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."OrderStatus_old"');
        await queryRunner.query('ALTER TABLE "order" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "order" DROP COLUMN "orderNumber"');
        await queryRunner.query('ALTER TABLE "order" ADD "orderNumber" character varying(32) NOT NULL');
        await queryRunner.query('ALTER TABLE "order" ADD CONSTRAINT "UQ_4e9f8dd16ec084bca97b3262edb" UNIQUE ("orderNumber")');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'UserRole\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."UserRole" RENAME TO "UserRole_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."users_role_enum" AS ENUM(\'user\', \'admin\', \'superuser\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT \'user\'');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."UserRole_old"');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'Gender\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."Gender" RENAME TO "Gender_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."users_gender_enum" AS ENUM(\'male\', \'female\', \'other\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "gender" TYPE "public"."users_gender_enum" USING "gender"::"text"::"public"."users_gender_enum"');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."Gender_old"');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'Region\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."Region" RENAME TO "Region_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."users_preferredregions_enum" AS ENUM(\'北部\', \'南部\', \'東部\', \'中部\', \'離島\', \'海外\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" TYPE "public"."users_preferredregions_enum"[] USING "preferredRegions"::"text"::"public"."users_preferredregions_enum"[]');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" SET DEFAULT \'{}\'');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."Region_old"');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'EventType\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."EventType" RENAME TO "EventType_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."users_preferredeventtypes_enum" AS ENUM(\'流行音樂\', \'搖滾\', \'電子音樂\', \'嘻哈\', \'爵士藍調\', \'古典音樂\', \'其他\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" TYPE "public"."users_preferredeventtypes_enum"[] USING "preferredEventTypes"::"text"::"public"."users_preferredeventtypes_enum"[]');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" SET DEFAULT \'{}\'');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."EventType_old"');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "searchHistory" SET DEFAULT \'[]\'');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "agentId" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "dayOfWeek" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "isActive" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" DROP COLUMN "createdAt"');
        await queryRunner.query('ALTER TABLE "supportSchedule" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "sessionType" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "status" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "priority" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "createdAt" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "sessionId" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "messageType" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "metadata" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "isRead" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "createdAt" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "tags" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" DROP COLUMN "embeddingVector"');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ADD "embeddingVector" jsonb');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "isActive" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "keywords" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "priority" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "relatedQuestions" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "viewCount" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "helpfulCount" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "notHelpfulCount" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "createdAt" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "updatedAt" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "updatedAt" DROP DEFAULT');
        await queryRunner.query('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE t.typname = \'PaymentStatus\' AND n.nspname = \'public\') THEN ALTER TYPE "public"."PaymentStatus" RENAME TO "PaymentStatus_old"; END IF; END $$');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."payment_status_enum" AS ENUM(\'pending\', \'completed\', \'failed\', \'refunded\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "status" TYPE "public"."payment_status_enum" USING "status"::"text"::"public"."payment_status_enum"');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."PaymentStatus_old"');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "currency" SET NOT NULL');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "payment" DROP COLUMN "tradeNo"');
        await queryRunner.query('ALTER TABLE "payment" ADD "tradeNo" character varying(50)');
        await queryRunner.query('DO $$ BEGIN CREATE TYPE "public"."concertReview_reviewstatus_enum" AS ENUM(\'pending\', \'approved\', \'rejected\', \'skipped\'); EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" TYPE "public"."concertReview_reviewstatus_enum" USING "reviewStatus"::"text"::"public"."concertReview_reviewstatus_enum"');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" SET DEFAULT \'pending\'');
        await queryRunner.query('DROP TYPE IF EXISTS "public"."ReviewStatus_old"');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "createdAt" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "updatedAt" DROP DEFAULT');
        await queryRunner.query('CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") ');
        await queryRunner.query('CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") ');
        await queryRunner.query('ALTER TABLE "organization" ADD CONSTRAINT "FK_b0d30285f6775593196167e2016" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concert" ADD CONSTRAINT "FK_30c544cde81f6c376020c0f5b90" FOREIGN KEY ("organizationId") REFERENCES "organization"("organizationId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concert" ADD CONSTRAINT "FK_b8c97e75c80a18f687bbaa72871" FOREIGN KEY ("venueId") REFERENCES "venues"("venueId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concert" ADD CONSTRAINT "FK_21bd010735c7e4adc27ff46d697" FOREIGN KEY ("locationTagId") REFERENCES "locationTag"("locationTagId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concert" ADD CONSTRAINT "FK_a52c799209e63921d3e5e32e5ae" FOREIGN KEY ("musicTagId") REFERENCES "musicTag"("musicTagId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concertSession" ADD CONSTRAINT "FK_5d96d235356b939822ad3c5f732" FOREIGN KEY ("concertId") REFERENCES "concert"("concertId") ON DELETE CASCADE ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "ticketType" ADD CONSTRAINT "FK_cde1aa9f6bf424b8484ad1b0fae" FOREIGN KEY ("concertSessionId") REFERENCES "concertSession"("sessionId") ON DELETE CASCADE ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "ticket" ADD CONSTRAINT "FK_8f4c2f0a2877e526e8881b51464" FOREIGN KEY ("orderId") REFERENCES "order"("orderId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "ticket" ADD CONSTRAINT "FK_7061359da242fbf565771953137" FOREIGN KEY ("ticketTypeId") REFERENCES "ticketType"("ticketTypeId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "ticket" ADD CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "order" ADD CONSTRAINT "FK_36369a70c27d63a464ebf2c8599" FOREIGN KEY ("ticketTypeId") REFERENCES "ticketType"("ticketTypeId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "order" ADD CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "supportSchedule" ADD CONSTRAINT "FK_3f522d47e7adb35662a63bc2eae" FOREIGN KEY ("agentId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "supportSession" ADD CONSTRAINT "FK_e3777806b6d44c36bfedd181f6d" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "supportSession" ADD CONSTRAINT "FK_5cc982d17cabf70598ded04ec34" FOREIGN KEY ("agentId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "supportMessage" ADD CONSTRAINT "FK_e572ce51d8c47cbebc1f9140c03" FOREIGN KEY ("sessionId") REFERENCES "supportSession"("supportSessionId") ON DELETE NO ACTION ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "supportMessage" ADD CONSTRAINT "FK_df28f55020d0a745cbbd6c0f4db" FOREIGN KEY ("senderId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "payment" ADD CONSTRAINT "FK_d09d285fe1645cd2f0db811e293" FOREIGN KEY ("orderId") REFERENCES "order"("orderId") ON DELETE RESTRICT ON UPDATE NO ACTION');
        await queryRunner.query('ALTER TABLE "concertReview" ADD CONSTRAINT "FK_0f8381f147592d49a3ca328caa3" FOREIGN KEY ("concertId") REFERENCES "concert"("concertId") ON DELETE CASCADE ON UPDATE NO ACTION');
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('ALTER TABLE "concertReview" DROP CONSTRAINT "FK_0f8381f147592d49a3ca328caa3"');
        await queryRunner.query('ALTER TABLE "payment" DROP CONSTRAINT "FK_d09d285fe1645cd2f0db811e293"');
        await queryRunner.query('ALTER TABLE "supportMessage" DROP CONSTRAINT "FK_df28f55020d0a745cbbd6c0f4db"');
        await queryRunner.query('ALTER TABLE "supportMessage" DROP CONSTRAINT "FK_e572ce51d8c47cbebc1f9140c03"');
        await queryRunner.query('ALTER TABLE "supportSession" DROP CONSTRAINT "FK_5cc982d17cabf70598ded04ec34"');
        await queryRunner.query('ALTER TABLE "supportSession" DROP CONSTRAINT "FK_e3777806b6d44c36bfedd181f6d"');
        await queryRunner.query('ALTER TABLE "supportSchedule" DROP CONSTRAINT "FK_3f522d47e7adb35662a63bc2eae"');
        await queryRunner.query('ALTER TABLE "order" DROP CONSTRAINT "FK_caabe91507b3379c7ba73637b84"');
        await queryRunner.query('ALTER TABLE "order" DROP CONSTRAINT "FK_36369a70c27d63a464ebf2c8599"');
        await queryRunner.query('ALTER TABLE "ticket" DROP CONSTRAINT "FK_0e01a7c92f008418bad6bad5919"');
        await queryRunner.query('ALTER TABLE "ticket" DROP CONSTRAINT "FK_7061359da242fbf565771953137"');
        await queryRunner.query('ALTER TABLE "ticket" DROP CONSTRAINT "FK_8f4c2f0a2877e526e8881b51464"');
        await queryRunner.query('ALTER TABLE "ticketType" DROP CONSTRAINT "FK_cde1aa9f6bf424b8484ad1b0fae"');
        await queryRunner.query('ALTER TABLE "concertSession" DROP CONSTRAINT "FK_5d96d235356b939822ad3c5f732"');
        await queryRunner.query('ALTER TABLE "concert" DROP CONSTRAINT "FK_a52c799209e63921d3e5e32e5ae"');
        await queryRunner.query('ALTER TABLE "concert" DROP CONSTRAINT "FK_21bd010735c7e4adc27ff46d697"');
        await queryRunner.query('ALTER TABLE "concert" DROP CONSTRAINT "FK_b8c97e75c80a18f687bbaa72871"');
        await queryRunner.query('ALTER TABLE "concert" DROP CONSTRAINT "FK_30c544cde81f6c376020c0f5b90"');
        await queryRunner.query('ALTER TABLE "organization" DROP CONSTRAINT "FK_b0d30285f6775593196167e2016"');
        await queryRunner.query('DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"');
        await queryRunner.query('DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "updatedAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('CREATE TYPE "public"."ReviewStatus_old" AS ENUM(\'pending\', \'approved\', \'rejected\', \'skipped\')');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" TYPE "public"."ReviewStatus_old" USING "reviewStatus"::"text"::"public"."ReviewStatus_old"');
        await queryRunner.query('ALTER TABLE "concertReview" ALTER COLUMN "reviewStatus" SET DEFAULT \'pending\'');
        await queryRunner.query('DROP TYPE "public"."concertReview_reviewstatus_enum"');
        await queryRunner.query('ALTER TABLE "payment" DROP COLUMN "tradeNo"');
        await queryRunner.query('ALTER TABLE "payment" ADD "tradeNo" character varying');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "currency" DROP NOT NULL');
        await queryRunner.query('CREATE TYPE "public"."PaymentStatus_old" AS ENUM(\'pending\', \'completed\', \'failed\', \'refunded\')');
        await queryRunner.query('ALTER TABLE "payment" ALTER COLUMN "status" TYPE "public"."PaymentStatus_old" USING "status"::"text"::"public"."PaymentStatus_old"');
        await queryRunner.query('DROP TYPE "public"."payment_status_enum"');
        await queryRunner.query('ALTER TYPE "public"."PaymentStatus_old" RENAME TO "PaymentStatus"');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "updatedAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "updatedAt" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "createdAt" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "notHelpfulCount" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "helpfulCount" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "viewCount" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "relatedQuestions" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "priority" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "keywords" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "isActive" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" DROP COLUMN "embeddingVector"');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ADD "embeddingVector" vector');
        await queryRunner.query('ALTER TABLE "supportKnowledgeBase" ALTER COLUMN "tags" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "createdAt" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "isRead" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "metadata" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "messageType" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportMessage" ALTER COLUMN "sessionId" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "createdAt" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "priority" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "status" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSession" ALTER COLUMN "sessionType" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" DROP COLUMN "createdAt"');
        await queryRunner.query('ALTER TABLE "supportSchedule" ADD "createdAt" TIMESTAMP DEFAULT now()');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "isActive" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "dayOfWeek" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "supportSchedule" ALTER COLUMN "agentId" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "searchHistory" DROP DEFAULT');
        await queryRunner.query('CREATE TYPE "public"."EventType_old" AS ENUM(\'流行音樂\', \'搖滾\', \'電子音樂\', \'嘻哈\', \'爵士藍調\', \'古典音樂\', \'其他\')');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" TYPE "public"."EventType_old"[] USING "preferredEventTypes"::"text"::"public"."EventType_old"[]');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredEventTypes" SET DEFAULT \'{}\'');
        await queryRunner.query('DROP TYPE "public"."users_preferredeventtypes_enum"');
        await queryRunner.query('ALTER TYPE "public"."EventType_old" RENAME TO "EventType"');
        await queryRunner.query('CREATE TYPE "public"."Region_old" AS ENUM(\'北部\', \'南部\', \'東部\', \'中部\', \'離島\', \'海外\')');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" TYPE "public"."Region_old"[] USING "preferredRegions"::"text"::"public"."Region_old"[]');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "preferredRegions" SET DEFAULT \'{}\'');
        await queryRunner.query('DROP TYPE "public"."users_preferredregions_enum"');
        await queryRunner.query('ALTER TYPE "public"."Region_old" RENAME TO "Region"');
        await queryRunner.query('CREATE TYPE "public"."Gender_old" AS ENUM(\'male\', \'female\', \'other\')');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "gender" TYPE "public"."Gender_old" USING "gender"::"text"::"public"."Gender_old"');
        await queryRunner.query('DROP TYPE "public"."users_gender_enum"');
        await queryRunner.query('ALTER TYPE "public"."Gender_old" RENAME TO "Gender"');
        await queryRunner.query('CREATE TYPE "public"."UserRole_old" AS ENUM(\'user\', \'admin\', \'superuser\')');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."UserRole_old" USING "role"::"text"::"public"."UserRole_old"');
        await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT \'user\'');
        await queryRunner.query('DROP TYPE "public"."users_role_enum"');
        await queryRunner.query('ALTER TYPE "public"."UserRole_old" RENAME TO "UserRole"');
        await queryRunner.query('ALTER TABLE "order" DROP CONSTRAINT "UQ_4e9f8dd16ec084bca97b3262edb"');
        await queryRunner.query('ALTER TABLE "order" DROP COLUMN "orderNumber"');
        await queryRunner.query('ALTER TABLE "order" ADD "orderNumber" character varying');
        await queryRunner.query('ALTER TABLE "order" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('CREATE TYPE "public"."OrderStatus_old" AS ENUM(\'held\', \'expired\', \'paid\', \'cancelled\', \'refunded\')');
        await queryRunner.query('ALTER TABLE "order" ALTER COLUMN "orderStatus" TYPE "public"."OrderStatus_old" USING "orderStatus"::"text"::"public"."OrderStatus_old"');
        await queryRunner.query('DROP TYPE "public"."order_orderstatus_enum"');
        await queryRunner.query('ALTER TYPE "public"."OrderStatus_old" RENAME TO "OrderStatus"');
        await queryRunner.query('CREATE TYPE "public"."TicketStatus_old" AS ENUM(\'purchased\', \'refunded\', \'used\')');
        await queryRunner.query('ALTER TABLE "ticket" ALTER COLUMN "status" TYPE "public"."TicketStatus_old" USING "status"::"text"::"public"."TicketStatus_old"');
        await queryRunner.query('DROP TYPE "public"."ticket_status_enum"');
        await queryRunner.query('ALTER TYPE "public"."TicketStatus_old" RENAME TO "TicketStatus"');
        await queryRunner.query('ALTER TABLE "ticketType" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "concertSession" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "updatedAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "visitCount" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" TYPE "public"."ReviewStatus_old" USING "reviewStatus"::"text"::"public"."ReviewStatus_old"');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "reviewStatus" SET DEFAULT \'skipped\'');
        await queryRunner.query('DROP TYPE "public"."concert_reviewstatus_enum"');
        await queryRunner.query('ALTER TYPE "public"."ReviewStatus_old" RENAME TO "ReviewStatus"');
        await queryRunner.query('CREATE TYPE "public"."ConInfoStatus_old" AS ENUM(\'draft\', \'reviewing\', \'published\', \'rejected\', \'finished\')');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" DROP DEFAULT');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" TYPE "public"."ConInfoStatus_old" USING "conInfoStatus"::"text"::"public"."ConInfoStatus_old"');
        await queryRunner.query('ALTER TABLE "concert" ALTER COLUMN "conInfoStatus" SET DEFAULT \'draft\'');
        await queryRunner.query('DROP TYPE "public"."concert_coninfostatus_enum"');
        await queryRunner.query('ALTER TYPE "public"."ConInfoStatus_old" RENAME TO "ConInfoStatus"');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "refundPolicy"');
        await queryRunner.query('ALTER TABLE "concert" ADD "refundPolicy" character varying(1000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "precautions"');
        await queryRunner.query('ALTER TABLE "concert" ADD "precautions" character varying(2000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "ticketPurchaseMethod"');
        await queryRunner.query('ALTER TABLE "concert" ADD "ticketPurchaseMethod" character varying(1000)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "conAddress"');
        await queryRunner.query('ALTER TABLE "concert" ADD "conAddress" character varying(200)');
        await queryRunner.query('ALTER TABLE "concert" DROP COLUMN "conIntroduction"');
        await queryRunner.query('ALTER TABLE "concert" ADD "conIntroduction" character varying(3000)');
        await queryRunner.query('ALTER TABLE "organization" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "updatedAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "createdAt" SET DEFAULT now()');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "hasTransit" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "hasParking" DROP NOT NULL');
        await queryRunner.query('ALTER TABLE "venues" ALTER COLUMN "isAccessible" DROP NOT NULL');
    }

}
